name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Project
        run: |
          npm install
          npm run build
      - name: Deploy to Linode
        uses: appleboy/scp-action@master
        with:
          host: '139.162.11.222'
          username: 'root'
          password: 'P@ssw0rd2022!'
          port: 22
          source: './apps/web/.next, ./apps/web/*, ./apps/web/.*, ./apps/api, ./deploy.config.js, ./package*.json, ./turbo.json'
          target: '${{ secrets.SSH_FOLDER }}'
      - name: Run App
        uses: appleboy/ssh-action@master
        with:
          host: '139.162.11.222'
          username: 'root'
          password: 'P@ssw0rd2022!'
          port: 22
          script: |
            cd ${{ secrets.SSH_FOLDER }}
            npm install
            npx prisma migrate dev --schema=./apps/api/prisma/schema.prisma
            pm2 start npm --name "${{ secrets.PROJECT_NAME }}" -- run serve
